player_data_array = [
    {
        'name': 'PlayerOne',
        'score': 1500,
        'ping': 35,
        'team': 'Red',
        'deaths': 12,
        'frags': 45,
        'suicides': 1,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 3,
        'flags_recovered': 1,
        'frames_total': 123456
    },
    {
        'name': 'PlayerTwo',
        'score': 1200,
        'ping': 50,
        'team': 'Blue',
        'deaths': 15,
        'frags': 38,
        'suicides': 0,
        'teamkills': 1,
        'spectator': 0,
        'flags_captured': 2,
        'flags_recovered': 0,
        'frames_total': 123400
    },
    {
        'name': 'PlayerThree',
        'score': 1800,
        'ping': 28,
        'team': 'Red',
        'deaths': 8,
        'frags': 55,
        'suicides': 0,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 4,
        'flags_recovered': 2,
        'frames_total': 123500
    },
    {
        'name': 'PlayerFour',
        'score': 900,
        'ping': 65,
        'team': 'Blue',
        'deaths': 20,
        'frags': 25,
        'suicides': 2,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 1,
        'flags_recovered': 0,
        'frames_total': 123300
    },
    {
        'name': 'PlayerFive',
        'score': 1600,
        'ping': 40,
        'team': 'Red',
        'deaths': 10,
        'frags': 50,
        'suicides': 0,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 3,
        'flags_recovered': 1,
        'frames_total': 123480
    },
    {
        'name': 'PlayerSix',
        'score': 1100,
        'ping': 55,
        'team': 'Blue',
        'deaths': 18,
        'frags': 32,
        'suicides': 1,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 2,
        'flags_recovered': 0,
        'frames_total': 123350
    },
    {
        'name': 'PlayerSeven',
        'score': 1400,
        'ping': 30,
        'team': 'Red',
        'deaths': 11,
        'frags': 40,
        'suicides': 0,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 2,
        'flags_recovered': 1,
        'frames_total': 123470
    },
    {
        'name': 'PlayerEight',
        'score': 800,
        'ping': 70,
        'team': 'Blue',
        'deaths': 25,
        'frags': 20,
        'suicides': 3,
        'teamkills': 1,
        'spectator': 0,
        'flags_captured': 0,
        'flags_recovered': 0,
        'frames_total': 123280
    },
    {
        'name': 'PlayerNine',
        'score': 1700,
        'ping': 32,
        'team': 'Red',
        'deaths': 9,
        'frags': 60,
        'suicides': 0,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 5,
        'flags_recovered': 2,
        'frames_total': 123520
    },
    {
        'name': 'PlayerTen',
        'score': 1000,
        'ping': 60,
        'team': 'Blue',
        'deaths': 19,
        'frags': 28,
        'suicides': 1,
        'teamkills': 0,
        'spectator': 0,
        'flags_captured': 1,
        'flags_recovered': 0,
        'frames_total': 123320
    }
]